test_site/news/urls.py
from django.conf.urls import url 
from . import views

urlpatterns = [
    url(r'^$', views.meldungen, name='meldungen'),
    url(r'^(?P<meldungs_id>\d+)/$', views.meldungen_detail, name='meldungen_detail'),
]

test_site/test_site/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls import url


urlpatterns = [
    url(r'^meldungen/', include(('news.urls', 'news'), namespace='news')),
    path(r'admin/', admin.site.urls),
]

test_site/news/models.py
from django.db import models

# Create your models here.

class Meldung(models.Model):
    titel = models.CharField(max_length=100)
    zeitstempel = models.DateTimeField()
    text = models.TextField('Meldungstext')
    def __str__(self):
        return self.titel


class Kommentar(models.Model):
    meldung = models.ForeignKey(Meldung, on_delete=models.CASCADE)
    autor = models.CharField(max_length=70)
    text = models.TextField('Kommentartext')
    def __str__(self):
        return "{} sagt '{}'".format(self.autor, self.text)

test_site/news/views.py
from django.shortcuts import render

# Create your views here.

from django.http import HttpResponse, Http404
from django.template import loader

from .models import Meldung, Kommentar

def meldungen(request):
    template = loader.get_template('news/meldungen.html')
    context = {'meldungen' : Meldung.objects.all()}
    return HttpResponse(template.render(context))


def meldungen_detail(request, meldungs_id):
    try:
        m = Meldung.objects.get(id=meldungs_id)
    except Meldung.DoesNotExist:
        raise Http404
    zeilen =[]
    zeilen.append("Meldung: '{}' vom {}".format(
        m.titel, m.zeitstempel.strftime('%d.%m.%Y um %H:%M')
    ))
    zeilen.append('Text: {}'.format(m.text))
    zeilen.append('Anzahl Kommentare: {}'.format(m.kommentar_set.count()))
    zeilen += ['', '-' * 30,
    'Kommentare:', '']
    zeilen += ['{}: {}'.format(k.autor, k.text) for k in m.kommentar_set.all()]
    antwort = HttpResponse('\n'.join(zeilen))
    antwort['Content-Type'] = 'text/plain'
    return antwort

test_site/news/templates/news/meldungen.html
{% extends 'main/basic.html' %}
{% block titel %}News-&Uuml;bersicht{% endblock %}
{% block inhalt %}
    {% for m in meldungen %}
        <div class="container" style="border: solid; margin: 1em;">
            <div class="titelzeile">
                <div class="titel" style="font-weight: bold; background-color: darkgray;">{{ m.titel|escape }}</div>
                <div class="zeitstempel">
                    {{ m.zeitstempel|date:'Y.m.d' }} um
                    {{ m.zeitstempel|time:'H:i' }} Uhr
                </div>
                <div style="clear: both"></div>
            </div>
            <div class="text">
                {{ m.text|escape|linebreaksbr }}
                <div class="link_unten">
                    <a href="{% url 'news:meldungen_detail' m.id %}">Details</a>
                </div>
            </div>
        </div>
    {% endfor %}
{% endblock %}

test_site/test_site/templates/main/basic.html
<!DOCTYPE html>
<html>
<head>
    <title>Unsere Django-Seite</title>
    <style type="text/css">
    </style>
</head>
<body>
    <div id="inhalt">
        <h2>{% block titel %}Django Beispielseite{% endblock %}</h2>
        {% block inhalt %}
        {% endblock %}
    </div>
</body>
</html>